config/routes.rb
ThirdProject::Application.routes.draw do

  resources :page_requests
  post '/like' => 'pict#like', :as => :click_like
  devise_for :users, :controllers => { :sessions => :sessions }
  get '/categories' => 'categories#index', :as =>:categories_list

  get '/categories/:name' => 'categories#show', :as => :categories
  get 'categories/:name/:id' => 'pict#show', :as => :pict
  get '/comment/all' => 'comment#all', :as => :comment_all
  get '/pict/all' => 'pict#all', :as => :pict_all
  get '/events' => 'events#index', :as => :events_list
  get '/events/:id/like' => 'events#like', :as => :event_like
  get '/events/:id/comment' => 'events#comment', :as => :event_comment
  get '/events/:id/sign_in' => 'events#sign', :as => :event_signin
  get '/events/:id/sign_out' => 'events#sign', :as => :event_signout
  get '/events/:id/navigation' => 'events#navigation', :as => :event_navigation

  post '/comment' => 'pict#comment'
  resources :user
  resources :comments
  resources :categories

  authenticated :user do
      root :to => redirect('/categories')
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

end

app/models/categories.rb
class Categories < ActiveRecord::Base
 has_many :picts
 def to_param
   name.parameterize
 end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :pict
  attr_accessible :pict_id, :user_id, :content
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id, :scope => :pict_id
  belongs_to :pict
  attr_accessible :pict_id, :user_id
end

app/models/page_request.rb
class PageRequest < ActiveRecord::Base
  attr_accessible :path
end

app/models/pict.rb
class Pict < ActiveRecord::Base
  has_many :likes
  has_many :comments
  belongs_to :categories
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "128x128>" }
  attr_accessible :like_count
  default_scope :order => 'like_count desc'
  #self.per_page = 10
end

app/models/sign_time.rb
class SignTime < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user_id, :sign_in, :login
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :likes
  has_many :comments
  has_many :sign_times
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :current_sign_out_at
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  require "will_paginate/array"

  def index
    @categories_all = Categories.all
  end
  def show
    #@current_categ = Categories.find_by_name(params[:name]).picts.paginate(params[:page])
    @current_categ = Categories.find_by_name(params[:name])
    @pictures = @current_categ.picts.paginate(:page => params[:page], :per_page => 5)
  end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def all
    @all_comments = Comment.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @users = User.all
  end

  def like
    @like_for_user = Like.find_all_by_user_id(params[:id])
  end

  def comment
    @pict_with_comment = Pict.includes(:comments).where("comments.user_id = ?", params[:id]).order('comments.pict_id')
  end

  def sign
    if params[:login]=="1"
      @first_sign = User.find(params[:id]).created_at
    end
    @sign = SignTime.find_all_by_user_id_and_login(params[:id], params[:login])
  end

  def navigation
    @stat_for_user = PageRequest.find_all_by_user_id(params[:id])
  end

end

app/controllers/page_requests_controller.rb
class PageRequestsController < ApplicationController
  def index
    @page_requests = PageRequest.all
  end
end

app/controllers/pict_controller.rb
class PictController < ApplicationController
  def show
    @pic = Pict.find(params[:id])
    @comment = Comment.new()
    @comments = Comment.find_all_by_pict_id(@pic.id)
  end

  def like
    @like = Like.new()
    @like.user_id = current_user.id
    @like.pict_id = params[:pic]
    @like.pict.update_attribute :like_count, @like.pict.like_count.to_i + 1
    @like.save
    redirect_to :back
  end

  def comment
    @comment = Comment.new()
    @comment.user_id = current_user.id
    @comment.pict_id = params[:comment][:pic]
    @comment.content = params[:comment][:content]
    @comment.save
    redirect_to :back
  end

  def all
    @pic = Pict.all
  end

end

app/controllers/sessions_controller.rb
# Rails.root/app/controllers/sessions.rb
class SessionsController < Devise::SessionsController

  def create
    if current_user
      @cur_sess = SignTime.new()
      @cur_sess.user_id = current_user.id
      @cur_sess.sign = Time.now
      @cur_sess.login = true
      @cur_sess.save
    end
    super
  end
  def destroy
    @cur_sess = SignTime.new()
    @cur_sess.user_id = current_user.id
    @cur_sess.sign = Time.now
    @cur_sess.login = false
    @cur_sess.save
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/page_requests_helper.rb
module PageRequestsHelper
end

app/views/categories/index.html.haml
%h2
  -@categories_all.each do |p|
    =link_to p.name, categories_path(p)

app/views/categories/show.html.haml
- @pictures.each do |p|
  = link_to image_tag(p.picture.url(:thumb)), pict_path(p, :name => @current_categ.name)

= will_paginate @pictures

app/views/comment/all.html.haml
%table
  - @all_comments.each do |comment|
    %tr
    %td= comment.user.email + "    " + comment.content

app/views/events/comment.html.haml
%table
  - @pict_with_comment.each do |pict|
    %tr
    %td=image_tag(pict.picture.url(:thumb))
    -pict.comments.each do |comment|
      %tr
      %td=comment.content

app/views/events/index.html.haml
%table
  -@users.each do |user|
    %tr
      %td= user.email
      %td= link_to "navigation", event_navigation_path(user, :id => user.id)
      %td= link_to "user sign in", event_signin_path(user, :id => user.id, :login => 1)
      %td= link_to "user sign out", event_signout_path(user, :id => user.id, :login => 0)
      %td= link_to "likes", event_like_path(user, :id => user.id)
      %td= link_to "comments", event_comment_path(user, :id => user.id)

app/views/events/like.html.haml
- @like_for_user.each do |like|
  = image_tag(like.pict.picture.url(:thumb))

app/views/events/navigation.html.haml
%table
  -@stat_for_user.each do |stat|
    %tr
      %td= stat.path
      %td=stat.created_at

app/views/events/sign.html.haml
-if @first_sign
  = @first_sign
  %br/
- @sign.each do |sign_cur|
  = sign_cur.sign
  %br/

app/views/layouts/application.html.haml
%html
  %head
    %title Super Gallery
    = stylesheet_link_tag 'web_app_theme'
    = javascript_include_tag :application
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          -if user_signed_in?
            = link_to "Home", root_path
            = link_to "Pictures", pict_all_path
            = link_to "Statistics", events_list_path
            = link_to "Comments", comment_all_path
        #user-navigation
          %ul.wat-cf
            - if user_signed_in?
              %li
                Signed in as #{current_user.email}
              %li
                =link_to "Sign out", destroy_user_session_path, :method => :delete
              %br
              %h1
            - else
              %li
                = link_to "Sign up", new_user_registration_path
                or #{link_to "sign in", new_user_session_path}
        #main-navigation
          %ul.wat-cf
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
        #sidebar
          = yield :sidebar

app/views/page_requests/index.html.haml
- title "Page Requests"
%table
  %tr
    %th Path
    %th Page Duration
    %th View Duration
    %th Db Duration
  - for page_request in @page_requests
    %tr
      %td= page_request.path
      %td= page_request.page_duration
      %td= page_request.view_duration
      %td= page_request.db_duration

app/views/pict/all.html.haml
- @pic.each do |pic|
  = image_tag(pic.picture.url(:thumb))

app/views/pict/show.html.haml
= image_tag @pic.picture
%br/
- if (Like.where user_id: current_user.id, pict_id: @pic.id).empty?
  = link_to "Like this", click_like_path(:pic => @pic.id), :method => 'post'
  %br/

-if @pic.like_count
  = "#{@pic.like_count} people's liked"

- @comments.each do |c|
  <hr>
  = c.content
  = c.user.email


= form_for @comment, :url => comment_path, :method => 'post' do |c|
  =c.text_field :content
  =c.hidden_field :pic, :value => @pic.id
  =c.submit "Ok"

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>